version: '3.3'

volumes:
   uploads-data:
   session-data:
   log-data:
   queue-data:
   jenkins-data:
   artifacts-data:

services:
   frontend:
     build: ./frontend
     ports:
     - "127.0.0.1:3000:3000"
     environment:
     - RABBITMQ_URL=${RABBITMQ_URL}
     - LOGDB_URL=${LOGDB_URL}
     - REDIS_URL=${REDIS_URL}
     - REDIS_EMAIL_URL=${REDIS_EMAIL_URL}
     - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
     - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
     - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
     - MAILGUN_API_KEY=${MAILGUN_API_KEY}
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
     - RHUB_BUILDER_URL=http://frontend:3000
     - RHUB_BUILDER_EXTERNAL_URL=http://127.0.0.1:3000
     - RHUB_ARTIFACTS_URL=${RHUB_ARTIFACTS_URL}
     - RHUB_EMAIL_FROM=${RHUB_EMAIL_FROM}
     volumes:
     - uploads-data:/usr/src/app/uploads
     depends_on:
     - redis
     - queue
     - logdb
     - jenkins
   backend:
     build: ./backend
     environment:
     - RABBITMQ_URL=${RABBITMQ_URL}
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
     - RHUB_ARTIFACTS=${RHUB_ARTIFACTS}
     depends_on:
     - queue
     - jenkins
   redis:
     image: "redis:4.0.11-alpine"
     ports:
     - "127.0.0.1:3001:6379"
     volumes:
     - session-data:/data
   queue:
     image: "rabbitmq:3.7.8-alpine"
     ports:
     - "127.0.0.1:3003:5672"
     volumes:
     - queue-data:/var/lib/rabbitmq
   logdb:
     image: "couchdb:2.2"
     ports:
     - "127.0.0.1:3002:5984"
     volumes:
     - log-data:/opt/couchdb/data
   logdb-seed:
     build: ./seed
     volumes:
      - ./seed/logdb:/seed
     environment:
     - LOGDB_URL=${LOGDB_URL}
     depends_on:
     - logdb
   jenkins:
     build: ./jenkins
     volumes:
     - jenkins-data:/var/jenkins_home
     environment:
     - JENKINS_ROOT_URL=${JENKINS_ROOT_URL}
     - JENKINS_USER=${JENKINS_USER}
     - JENKINS_PASSWORD=${JENKINS_PASSWORD}
     ports:
     - "127.0.0.1:8080:8080"
   linux-builder:
     hostname: linux-builder
     build: ./linux-builder
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - artifacts-data:/artifacts
     environment:
     - JENKINS_URL=http://jenkins:8080
     - JENKINS_USER=${JENKINS_USER}
     - JENKINS_PASSWORD=${JENKINS_PASSWORD}
     - RHUB_EXECUTORS=4
     - JENKINS_LABELS=swarm linux
     - RHUB_CRAN_MIRROR=${RHUB_CRAN_MIRROR}
     - RHUB_ARTIFACTS=${RHUB_ARTIFACTS}
   artifacts:
     build: ./artifacts
     volumes:
     - artifacts-data:/usr/local/apache2/htdocs
     ports:
     - 127.0.0.1:3004:80
   cron:
     build: ./cron
     environment:
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
