version: '3.3'

volumes:
   uploads-data:
   session-data:
   log-data:
   queue-data:
   jenkins-data:
   artifacts-data:

services:
   frontend:
     build: ./frontend
     environment:
     - RABBITMQ_URL=${RABBITMQ_URL}
     - LOGDB_URL=${LOGDB_URL}
     - REDIS_URL=${REDIS_URL}
     - REDIS_EMAIL_URL=${REDIS_EMAIL_URL}
     - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
     - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
     - RHUB_BUILDER_URL=http://frontend:3000
     - RHUB_BUILDER_EXTERNAL_URL=${RHUB_BUILDER_EXTERNAL_URL}
     - RHUB_ARTIFACTS_URL=${RHUB_ARTIFACTS_URL}
     - RHUB_EMAIL_FROM=${RHUB_EMAIL_FROM}
     - RHUB_EMAIL_MODE=${RHUB_EMAIL_MODE}
     - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
     - MAILGUN_API_KEY=${MAILGUN_API_KEY}
     - RHUB_SMTP_SERVER=${RHUB_SMTP_SERVER}
     - RHUB_SMTP_USERNAME=${RHUB_SMTP_USERNAME}
     - RHUB_SMTP_PASSWORD=${RHUB_SMTP_PASSWORD}
     - RHUB_SMTP_PORT=${RHUB_SMTP_PORT}
     - RHUB_SMTP_TLS_REQUIRED=${RHUB_SMTP_TLS_REQUIRED}
     volumes:
     - uploads-data:/usr/src/app/uploads
     depends_on:
     - redis
     - queue
     - logdb
     - jenkins
   backend:
     build: ./backend
     environment:
     - RABBITMQ_URL=${RABBITMQ_URL}
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
     - RHUB_ARTIFACTS=${RHUB_ARTIFACTS}
     depends_on:
     - queue
     - jenkins
   redis:
     image: "redis:4.0.11-alpine"
     volumes:
     - session-data:/data
   queue:
     image: "rabbitmq:3.7.8-alpine"
     volumes:
     - queue-data:/var/lib/rabbitmq
   logdb:
     image: "couchdb:2.2"
     volumes:
     - log-data:/opt/couchdb/data
   logdb-seed:
     build: ./seed
     environment:
     - LOGDB_URL=${LOGDB_URL}
     entrypoint:
     - bash
     - -c
     - /seed/logdb.sh
     depends_on:
     - logdb
   jenkins:
     build: ./jenkins
     volumes:
     - jenkins-data:/var/jenkins_home
     environment:
     - JENKINS_ROOT_URL=${JENKINS_ROOT_URL}
     - JENKINS_USER=${JENKINS_USER}
     - JENKINS_PASSWORD=${JENKINS_PASSWORD}
   linux-builder:
     hostname: linux-builder
     build: ./linux-builder
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - artifacts-data:/artifacts
     environment:
     - JENKINS_URL=http://jenkins:8080
     - JENKINS_USER=${JENKINS_USER}
     - JENKINS_PASSWORD=${JENKINS_PASSWORD}
     - RHUB_EXECUTORS=4
     - JENKINS_LABELS=swarm linux
     - RHUB_CRAN_MIRROR=${RHUB_CRAN_MIRROR}
     - RHUB_ARTIFACTS=${RHUB_ARTIFACTS}
   cron:
     build: ./cron
     environment:
     - JENKINS_URL=http://${JENKINS_USER}:${JENKINS_PASSWORD}@jenkins:8080
   nginx:
     build: ./nginx
     volumes:
     - artifacts-data:/artifacts:ro
     ports:
     - 80:80
     depends_on:
     - frontend
     entrypoint:
     - sh
     - -c
     - 'wait-for frontend:3000 -- nginx -g "daemon off;"'
